# col
# Autogenerated from man page /usr/share/man/man1/col.1.gz
complete -c col -s b -l no-backspaces -d 'Do not output any backspaces, printing only the last character written to eac…'
complete -c col -s f -l fine -d 'Permit half-forward line feeds'
complete -c col -s h -l tabs -d 'Output tabs instead of multiple spaces'
complete -c col -s l -l lines -d 'Buffer at least  number lines in memory.   By default, 128 lines are buffered'
complete -c col -s p -l pass -d 'Force unknown control sequences to be passed through unchanged'
complete -c col -s x -l spaces -d 'Output multiple spaces instead of tabs'
complete -c col -s V -l version -d 'Display version information and exit'
complete -c col -s H -l help -d 'Display help text and exit'

