# colcrt
# Autogenerated from man page /usr/share/man/man1/colcrt.1.gz
complete -c colcrt -l no-underlining -d 'Suppress all underlining'
complete -c colcrt -s 2 -l half-lines -d 'Causes all half-lines to be printed, effectively double spacing the output'
complete -c colcrt -s V -l version -d 'Display version information and exit'
complete -c colcrt -s h -l help -d 'Display help text and exit.  HISTORY The colcrt command appeared in 3. 0BSD'

