# colrm
# Autogenerated from man page /usr/share/man/man1/colrm.1.gz
complete -c colrm -s V -l version -d 'Display version information and exit'
complete -c colrm -s h -l help -d 'Display help text and exit.  HISTORY The colrm command appeared in 3. 0BSD'

