# dpkg-gencontrol
# Autogenerated from man page /usr/share/man/man1/dpkg-gencontrol.1.gz
complete -c dpkg-gencontrol -o vversion -d 'Sets the version number of the binary package which will be generated'
complete -c dpkg-gencontrol -o Vname -d 'Set an output substitution variable'
complete -c dpkg-gencontrol -o Tsubstvars-file -d 'Read substitution variables in substvars-file; the default is debian/substvars'
complete -c dpkg-gencontrol -o Dfield -d 'Override or add an output control file field'
complete -c dpkg-gencontrol -o Ufield -d 'Remove an output control file field'
complete -c dpkg-gencontrol -o ccontrol-file -d 'Specifies the main source control file to read information from'
complete -c dpkg-gencontrol -o lchangelog-file -d 'Specifies the changelog file to read information from'
complete -c dpkg-gencontrol -o ffiles-list-file -d 'Read or write the list of files to be uploaded here, rather than using debian…'
complete -c dpkg-gencontrol -o Fchangelog-format -d 'Specifies the format of the changelog'
complete -c dpkg-gencontrol -o ppackage -d 'Generate information for the binary package package'
complete -c dpkg-gencontrol -o nfilename -d 'Assume the filename of the package will be filename instead of the normal pac…'
complete -c dpkg-gencontrol -o is -o ip -o isp -d 'These options are ignored for compatibility with older versions of the dpkg b…'
complete -c dpkg-gencontrol -o Ppackage-build-dir -d 'Scan package-build-dir instead of debian/tmp'
complete -c dpkg-gencontrol -s O -d 'Print the control file to standard output (or filename if specified, since dp…'
complete -c dpkg-gencontrol -s '?' -l help -d 'Show the usage message and exit'

