# gh-codespace-ports-forward
# Autogenerated from man page /usr/share/man/man1/gh-codespace-ports-forward.1
complete -c gh-codespace-ports-forward -s c -l codespace -d '	Name of the codespace'
complete -c gh-codespace-ports-forward -l help -d '	Show help for command SEE ALSO'

