# gh-codespace-cp
# Autogenerated from man page /usr/share/man/man1/gh-codespace-cp.1
complete -c gh-codespace-cp -s c -l codespace -d '	Name of the codespace'
complete -c gh-codespace-cp -s e -l expand -d '	Expand remote file names on remote shell'
complete -c gh-codespace-cp -s r -l recursive -d '	Recursively copy directories OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-codespace-cp -l help -d '	Show help for command SEE ALSO'

