# gh-codespace-delete
# Autogenerated from man page /usr/share/man/man1/gh-codespace-delete.1
complete -c gh-codespace-delete -l all -d '	Delete all codespaces'
complete -c gh-codespace-delete -s c -l codespace -d '	Name of the codespace'
complete -c gh-codespace-delete -l days -d '	Delete codespaces older than N days'
complete -c gh-codespace-delete -s f -l force -d '	Skip confirmation for codespaces that contain unsaved changes'
complete -c gh-codespace-delete -s r -l repo -d '	Delete codespaces for a repository OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-codespace-delete -l help -d '	Show help for command SEE ALSO'

