# gh-codespace-ports-visibility
# Autogenerated from man page /usr/share/man/man1/gh-codespace-ports-visibility.1
complete -c gh-codespace-ports-visibility -s c -l codespace -d '	Name of the codespace'
complete -c gh-codespace-ports-visibility -l help -d '	Show help for command EXAMPLE gh codespace ports visibility 80:org 3000:priv…'

