# gh-codespace-create
# Autogenerated from man page /usr/share/man/man1/gh-codespace-create.1
complete -c gh-codespace-create -s b -l branch -d '	repository branch'
complete -c gh-codespace-create -s m -l machine -d '	hardware specifications for the VM'
complete -c gh-codespace-create -s r -l repo -d '	repository name with owner: user/repo'
complete -c gh-codespace-create -s s -l status -d '	show status of post-create command and dotfiles OPTIONS INHERITED FROM PAREN…'
complete -c gh-codespace-create -l help -d '	Show help for command SEE ALSO'

