# gh-codespace-stop
# Autogenerated from man page /usr/share/man/man1/gh-codespace-stop.1
complete -c gh-codespace-stop -s c -l codespace -d '	Name of the codespace OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-codespace-stop -l help -d '	Show help for command SEE ALSO'

