# gh-codespace-ports
# Autogenerated from man page /usr/share/man/man1/gh-codespace-ports.1
complete -c gh-codespace-ports -s c -l codespace -d '	Name of the codespace'
complete -c gh-codespace-ports -s q -l jq -d '	Filter JSON output using a jq expression'
complete -c gh-codespace-ports -l json -d '	Output JSON with the specified fields'
complete -c gh-codespace-ports -s t -l template -d '	Format JSON output using a Go template OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-codespace-ports -l help -d '	Show help for command SEE ALSO'

