# gh-codespace-list
# Autogenerated from man page /usr/share/man/man1/gh-codespace-list.1
complete -c gh-codespace-list -s q -l jq -d '	Filter JSON output using a jq expression'
complete -c gh-codespace-list -l json -d '	Output JSON with the specified fields'
complete -c gh-codespace-list -s L -l limit -d '	Maximum number of codespaces to list'
complete -c gh-codespace-list -s t -l template -d '	Format JSON output using a Go template OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-codespace-list -l help -d '	Show help for command SEE ALSO'

