# gh-codespace-ssh
# Autogenerated from man page /usr/share/man/man1/gh-codespace-ssh.1
complete -c gh-codespace-ssh -s c -l codespace -d '	Name of the codespace'
complete -c gh-codespace-ssh -s d -l debug -d '	Log debug data to a file'
complete -c gh-codespace-ssh -l debug-file -d '	Path of the file log to'
complete -c gh-codespace-ssh -l profile -d '	Name of the SSH profile to use'
complete -c gh-codespace-ssh -l server-port -d '	SSH server port number (0 => pick unused) OPTIONS INHERITED FROM PARENT COMM…'
complete -c gh-codespace-ssh -l help -d '	Show help for command SEE ALSO'

