# gh-extension-install
# Autogenerated from man page /usr/share/man/man1/gh-extension-install.1
complete -c gh-extension-install -l help -d '	Show help for command EXAMPLE $ gh extension install owner/gh-extension $ gh…'

