# gh-extension-upgrade
# Autogenerated from man page /usr/share/man/man1/gh-extension-upgrade.1
complete -c gh-extension-upgrade -l all -d '	Upgrade all extensions'
complete -c gh-extension-upgrade -l force -d '	Force upgrade extension OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-extension-upgrade -l help -d '	Show help for command SEE ALSO'

