# gh-pr-list
# Autogenerated from man page /usr/share/man/man1/gh-pr-list.1
complete -c gh-pr-list -s a -l assignee -d '	Filter by assignee'
complete -c gh-pr-list -s A -l author -d '	Filter by author'
complete -c gh-pr-list -s B -l base -d '	Filter by base branch'
complete -c gh-pr-list -s d -l draft -d '	Filter by draft state'
complete -c gh-pr-list -s H -l head -d '	Filter by head branch'
complete -c gh-pr-list -s q -l jq -d '	Filter JSON output using a jq expression'
complete -c gh-pr-list -l json -d '	Output JSON with the specified fields'
complete -c gh-pr-list -s l -l label -d '	Filter by labels'
complete -c gh-pr-list -s L -l limit -d '	Maximum number of items to fetch'
complete -c gh-pr-list -s S -l search -d '	Search pull requests with query'
complete -c gh-pr-list -s s -l state -d '	Filter by state: {open|closed|merged|all}'
complete -c gh-pr-list -s t -l template -d '	Format JSON output using a Go template'
complete -c gh-pr-list -s w -l web -d '	Open the browser to list the pull requests OPTIONS INHERITED FROM PARENT COM…'
complete -c gh-pr-list -l help -d '	Show help for command'
complete -c gh-pr-list -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format EXAMPLE List PR…'

