# gh-pr-ready
# Autogenerated from man page /usr/share/man/man1/gh-pr-ready.1
complete -c gh-pr-ready -l help -d '	Show help for command'
complete -c gh-pr-ready -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

