# gh-pr-diff
# Autogenerated from man page /usr/share/man/man1/gh-pr-diff.1
complete -c gh-pr-diff -l color -d '	Use color in diff output: {always|never|auto}'
complete -c gh-pr-diff -l patch -d '	Display diff in patch format OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-pr-diff -l help -d '	Show help for command'
complete -c gh-pr-diff -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

