# gh-run-rerun
# Autogenerated from man page /usr/share/man/man1/gh-run-rerun.1
complete -c gh-run-rerun -l help -d '	Show help for command'
complete -c gh-run-rerun -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

