# gh-repo-sync
# Autogenerated from man page /usr/share/man/man1/gh-repo-sync.1
complete -c gh-repo-sync -l force -d 'by synced using a hard reset'
complete -c gh-repo-sync -s b -l branch -d '	Branch to sync (default: main branch)'
complete -c gh-repo-sync -s s -l source -d '	Source repository OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-repo-sync -l help -d '	Show help for command EXAMPLE # Sync local repository from remote parent $ g…'

