# gh-repo-delete
# Autogenerated from man page /usr/share/man/man1/gh-repo-delete.1
complete -c gh-repo-delete -l confirm -d '	confirm deletion without prompting OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-repo-delete -l help -d '	Show help for command SEE ALSO'

