# gh-run
# Autogenerated from man page /usr/share/man/man1/gh-run.1
complete -c gh-run -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format OPTIONS INHERIT…'
complete -c gh-run -l help -d '	Show help for command SEE ALSO'

