# gh-ssh-key-add
# Autogenerated from man page /usr/share/man/man1/gh-ssh-key-add.1
complete -c gh-ssh-key-add -s t -l title -d '	Title for the new key OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-ssh-key-add -l help -d '	Show help for command SEE ALSO'

