# gh-workflow-disable
# Autogenerated from man page /usr/share/man/man1/gh-workflow-disable.1
complete -c gh-workflow-disable -l help -d '	Show help for command'
complete -c gh-workflow-disable -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

