# hd
# Autogenerated from man page /usr/share/man/man1/hd.1.gz
complete -c hd -s b -l one-byte-octal -d 'One-byte octal display'
complete -c hd -s c -l one-byte-char -d 'One-byte character display'
complete -c hd -s C -l canonical -d 'Canonical hex+ASCII display'
complete -c hd -s d -l two-bytes-decimal -d 'Two-byte decimal display'
complete -c hd -s e -l format -d 'Specify a format string to be used for displaying data'
complete -c hd -s f -l format-file -d 'Specify a file that contains one or more newline-separated format strings'
complete -c hd -s L -l color -d 'Accept color units for the output'
complete -c hd -s n -l length -d 'Interpret only  length bytes of input'
complete -c hd -s o -l two-bytes-octal -d 'Two-byte octal display'
complete -c hd -s s -l skip -d 'Skip  offset bytes from the beginning of the input'
complete -c hd -s v -l no-squeezing -d 'The  -v option causes  hexdump to display all input data'
complete -c hd -s x -l two-bytes-hex -d 'Two-byte hexadecimal display'
complete -c hd -s V -l version -d 'Display version information and exit'
complete -c hd -s h -l help -d 'Display help text and exit'

