# look
# Autogenerated from man page /usr/share/man/man1/look.1.gz
complete -c look -s a -l alternative -d 'Use the alternative dictionary file'
complete -c look -s d -l alphanum -d 'Use normal dictionary character set and order, i. e'
complete -c look -s f -l ignore-case -d 'Ignore the case of alphabetic characters'
complete -c look -s t -l terminate -d 'Specify a string termination character, i. e'
complete -c look -s V -l version -d 'Display version information and exit'
complete -c look -s h -l help -d 'Display help text and exit'

