# mkfs
# Autogenerated from man page /usr/share/man/man8/mkfs.minix.8.gz
complete -c mkfs -l check -d 'Check the device for bad blocks before creating the filesystem'
complete -c mkfs -l namelength -d 'Specify the maximum length of filenames'
complete -c mkfs -l badblocks -d 'Read the list of bad blocks from R filename '
complete -c mkfs -s 1 -d 'Make a Minix version 1 filesystem.   This is the default'
complete -c mkfs -s 2 -d 'Make a Minix version 2 filesystem'
complete -c mkfs -s 3 -d 'Make a Minix version 3 filesystem'

