# more
# Autogenerated from man page /usr/share/man/man1/more.1.gz
complete -c more -s d -l silent -d 'Prompt with "[Press space to continue, \'q\' to quit'
complete -c more -s l -l logical -d 'Do not pause after any line containing a  ^L (form feed)'
complete -c more -s f -l no-pause -d 'Count logical lines, rather than screen lines (i. e'
complete -c more -s p -l print-over -d 'Do not scroll.   Instead, clear the whole screen and then display the text'
complete -c more -s c -l clean-print -d 'Do not scroll'
complete -c more -s s -l squeeze -d 'Squeeze multiple blank lines into one'
complete -c more -s u -l plain -d 'Suppress underlining'
complete -c more -s n -l lines -d 'Specify the  number of lines per screenful'
complete -c more -l help -d 'Display help text and exit'
complete -c more -s V -l version -d 'Display version information and exit'

