# scriptreplay
# Autogenerated from man page /usr/share/man/man1/scriptreplay.1.gz
complete -c scriptreplay -s I -l log-in -d 'File containing script\'s terminal input'
complete -c scriptreplay -s O -l log-out -d 'File containing script\'s terminal output'
complete -c scriptreplay -s B -l log-io -d 'File containing script\'s terminal output and input'
complete -c scriptreplay -s t -l timing -d 'File containing script\'s timing output'
complete -c scriptreplay -s T -l log-timing -d 'This is an alias for -t, maintained for compatibility with  script (1) comman…'
complete -c scriptreplay -s s -l typescript -d 'File containing script\'s terminal output.   Deprecated alias to --log-out'
complete -c scriptreplay -s c -l cr-mode -d 'Specifies how to use the CR (0x0D, carriage return) character from log files'
complete -c scriptreplay -s d -l divisor -d 'Speed up the replay displaying this  number of times'
complete -c scriptreplay -s m -l maxdelay -d 'Set the maximum delay between updates to  number of seconds'
complete -c scriptreplay -l summary -d 'Display details about the session recorded in the specified timing file and e…'
complete -c scriptreplay -s x -l stream -d 'Forces  scriptreplay to print only the specified stream'
complete -c scriptreplay -s V -l version -d 'Display version information and exit'
complete -c scriptreplay -s h -l help -d 'Display help text and exit.  EXAMPLES'

