# scriptlive
# Autogenerated from man page /usr/share/man/man1/scriptlive.1.gz
complete -c scriptlive -s I -l log-in -d 'File containing script\'s terminal input'
complete -c scriptlive -s B -l log-io -d 'File containing script\'s terminal output and input'
complete -c scriptlive -s t -l timing -d 'File containing script\'s timing output'
complete -c scriptlive -s T -l log-timing -d 'Aliased to -t, maintained for compatibility with  script (1) command-line opt…'
complete -c scriptlive -s d -l divisor -d 'Speed up the replay displaying this  number of times'
complete -c scriptlive -s m -l maxdelay -d 'Set the maximum delay between updates to  number of seconds'
complete -c scriptlive -s V -l version -d 'Display version information and exit'
complete -c scriptlive -s h -l help -d 'Display help text and exit.  EXAMPLES'

