# tasksel
# Autogenerated from man page /usr/share/man/man8/tasksel.8.gz
complete -c tasksel -s t -l test -d 'test mode; don\'t actually install or remove packages'
complete -c tasksel -l new-install -d 'automatically select some tasks without even displaying them to the user; def…'
complete -c tasksel -l list-tasks -d 'list on stdout the tasks that would be displayed in the tasksel interface'
complete -c tasksel -l task-packages -d 'lists on stdout the packages that are available and part of the given task '
complete -c tasksel -l task-desc -d 'outputs the extended description of the given task'

