# termit
# Autogenerated from man page /usr/share/man/man1/termit.1.gz
complete -c termit -s h
complete -c termit -l help
complete -c termit -s v
complete -c termit -l version
complete -c termit -s e
complete -c termit -l execute -d '= cmd'
complete -c termit -s i
complete -c termit -l init -d '= file'
complete -c termit -s n
complete -c termit -l name -d '= name'
complete -c termit -s c
complete -c termit -l class -d '= class'
complete -c termit -s r
complete -c termit -l role -d '= role'
complete -c termit -s T
complete -c termit -l title -d '= title'

