# ul
# Autogenerated from man page /usr/share/man/man1/ul.1.gz
complete -c ul -s i -l indicated -d 'Underlining is indicated by a separate line containing appropriate dashes `-\'…'
complete -c ul -s t -s T -l terminal -d 'Override the environment variable  TERM with the specified  terminal type'
complete -c ul -s V -l version -d 'Display version information and exit'
complete -c ul -s h -l help -d 'Display help text and exit'

