# x-terminal-emulator
# Autogenerated from man page /usr/share/man/man1/x-terminal-emulator.1.gz
complete -c x-terminal-emulator -s h
complete -c x-terminal-emulator -l help
complete -c x-terminal-emulator -s v
complete -c x-terminal-emulator -l version
complete -c x-terminal-emulator -s e
complete -c x-terminal-emulator -l execute -d '= cmd'
complete -c x-terminal-emulator -s i
complete -c x-terminal-emulator -l init -d '= file'
complete -c x-terminal-emulator -s n
complete -c x-terminal-emulator -l name -d '= name'
complete -c x-terminal-emulator -s c
complete -c x-terminal-emulator -l class -d '= class'
complete -c x-terminal-emulator -s r
complete -c x-terminal-emulator -l role -d '= role'
complete -c x-terminal-emulator -s T
complete -c x-terminal-emulator -l title -d '= title'

